LT = "<"
LTE = "<="
EQ = "=="
NE = "!="
GT = ">"
GTE = ">="
ARRAY_CONTAINS = "array_contains"
ARRAY_CONTAINS_ANY = "array_contains_any"
IN = "in"
NOT_IN = "not-in"
# Combine a list of filter dicts, e.g. {OR: [{"a": 1}, {"b": {GTE: 2}}]}
OR = "$or"
AND = "$and"
